name: Release to PyPI and GitHub

on:
  push:
    # Trigger on version tag pushes, e.g. v0.2.0
    tags:
      - 'v*.*.*'

jobs:
  release:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build tools
        run: python -m pip install --upgrade build twine

      - name: Build distributions
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          # Upload all distribution files
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}